# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sending_letter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMenuBar, QMenu, QFileDialog, QMessageBox
import os
from zipfile import ZipFile
import getpass
from mail import Email


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                 "color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setObjectName("gridLayout")
        self.fileSearch = QtWidgets.QToolButton(self.centralwidget)
        self.fileSearch.setStyleSheet("border: 1px solid white;")
        self.fileSearch.setObjectName("fileSearch")
        self.gridLayout.addWidget(self.fileSearch, 0, 1, 1, 1)
        self.filePath = QtWidgets.QLineEdit(self.centralwidget)
        self.filePath.setObjectName("filePath")
        self.gridLayout.addWidget(self.filePath, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(15, 0, 15, 15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.theme = QtWidgets.QLineEdit(self.centralwidget)
        self.theme.setObjectName("theme")
        self.gridLayout_3.addWidget(self.theme, 1, 1, 1, 1)
        self.labelText = QtWidgets.QLabel(self.centralwidget)
        self.labelText.setObjectName("labelText")
        self.gridLayout_3.addWidget(self.labelText, 2, 0, 1, 1)
        self.text = QtWidgets.QTextEdit(self.centralwidget)
        self.text.setStyleSheet("")
        self.text.setObjectName("text")
        self.gridLayout_3.addWidget(self.text, 2, 1, 1, 1)
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setObjectName("email")
        self.gridLayout_3.addWidget(self.email, 0, 1, 1, 1)
        self.labelTheme = QtWidgets.QLabel(self.centralwidget)
        self.labelTheme.setObjectName("labelTheme")
        self.gridLayout_3.addWidget(self.labelTheme, 1, 0, 1, 1)
        self.labelEmail = QtWidgets.QLabel(self.centralwidget)
        self.labelEmail.setObjectName("labelEmail")
        self.gridLayout_3.addWidget(self.labelEmail, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setStyleSheet("")
        self.btn.setObjectName("btn")
        self.gridLayout_5.addWidget(self.btn, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # моя функция
        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "sending letter"))
        self.fileSearch.setText(_translate("MainWindow", "..."))
        self.labelText.setText(_translate("MainWindow", "Текс сообщения:"))
        self.labelTheme.setText(_translate("MainWindow", "Тема сообщения:"))
        self.labelEmail.setText(_translate("MainWindow", "E-mail:"))
        self.btn.setText(_translate("MainWindow", "Отправить"))

    def add_functions(self):
        self.fileSearch.clicked.connect(
            lambda: self.action_clicked())
        self.btn.clicked.connect(
            lambda: self.dispatch())

    def action_clicked(self):
        # [0] выбираем первый файл
        filePath = QFileDialog.getOpenFileName()[0]
        self.filePath.setText(filePath)

    def dispatch(self):
        dirFolder = os.getenv("SystemDrive") + '\\Users\\' + \
            getpass.getuser() + '\\Desktop\\test.zip'
        self.createZipFile(dirFolder)
        self.sendingMessage(dirFolder)

    def createZipFile(self, dirFolder):
        fileName = os.path.basename(self.filePath.text())
        try:
            with ZipFile(dirFolder, "w") as newzip:
                newzip.write(fileName)
        except FileNotFoundError:
            print("No such file")

    def sendingMessage(self, dirFolder):
        email_to = self.email.text()
        theme_message = self.theme.text()
        text_message = self.text.toPlainText()

        email = Email()
        files = [dirFolder]

        try:
            email.send_email(email_to, theme_message,
                             text_message, files)
            # Всплывающее окно
            success = QMessageBox()
            success.setWindowTitle("Успех!")
            success.setText("Письмо отправленно! Поздравляю :)")
            success.setIcon(QMessageBox.Information)
            # | - разделяет кнопки, первая кнопка будет подсвечиваться
            success.setStandardButtons(QMessageBox.Ok)

            # вывод окна
            success.exec_()
        except:
            # Всплывающее окно
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Неизвестная ошибка. Может неверно ввели e-mail")
            error.setIcon(QMessageBox.Warning)
            # | - разделяет кнопки, первая кнопка будет подсвечиваться
            error.setStandardButtons(QMessageBox.Ok)

            # вывод окна
            error.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
