import copy  # вызов модуля copy
n = int(input('Количество элементов в N множителе: '))
m = int(input('Количество элементов в M множителе: '))
N = set()
M = set()
for i in range(n):
    wn = input('Элемент '+str(i+1)+' N: ')
    N.add(wn)
for j in range(m):
    wm = input('Элемент '+str(j+1)+' M: ')
    M.add(wm)
print('N:', N)
print('M:', M)
N1 = copy.copy(N)  # копирует объект
M1 = copy.copy(M)
N2 = copy.copy(N)
M2 = copy.copy(M)
N3 = copy.copy(N)
N.update(M)
print('Объединение этих множеств:', N)
N1.intersection_update(M1)
print('Все элементы, которые повторяются в N и M:', N1)
N2.difference_update(M2)
M2.difference_update(N3)
N2.update(M2)
print('Множество из элементов, которые есть в N, но нет в M и есть в M, но нет в N:', N2)
delete = input('Удалить элемент множества: ')
N2.discard(delete)
print(N2)
