# Generated by Django 3.2.3 on 2021-05-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20210521_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, verbose_name='Данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartProducts', to='myshop.product')),
            ],
        ),
    ]
