# Generated by Django 3.2.3 on 2021-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_alter_cartproduct_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='key',
            field=models.TextField(default=1, verbose_name='Ключ'),
            preserve_default=False,
        ),
    ]
