# Generated by Django 3.2.3 on 2021-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_cartproduct_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='data',
            field=models.TextField(blank=True, default='{}', verbose_name='Данные'),
        ),
    ]
