# Generated by Django 3.2.3 on 2021-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_alter_cartproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные'),
        ),
    ]
