# Как конвертировать из ui в py? Команда: python -m PyQt5.uic.pyuic -x калькулятор.ui -o калькулятор.py
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'калькулятор.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 470)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 140, 239, 220))
        self.gridLayoutWidget.setStyleSheet("QPushButton{\n"
                                            "background-color: white;\n"
                                            "width: 75px;\n"
                                            "height: 50px;\n"
                                            "font-size: 14px;\n"
                                            "font-weight: bold;\n"
                                            "border: None;\n"
                                            "text-align: center;\n"
                                            "}\n"
                                            "QPushButton:hover{\n"
                                            "background-color: silver;\n"
                                            "}\n"
                                            "QPushButton:pressed{\n"
                                            "background-color: red;\n"
                                            "}")
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "background-color: white;\n"
                                      "width: 75px;\n"
                                      "height: 50px;\n"
                                      "font-size: 14px;\n"
                                      "font-weight: bold;\n"
                                      "border: None;\n"
                                      "text-align: center;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color: silver;\n"
                                      "}\n"
                                      "QPushButton:pressed{\n"
                                      "background-color: red;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "background-color: white;\n"
                                        "width: 75px;\n"
                                        "height: 50px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "border: None;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: silver;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: red;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "background-color: white;\n"
                                        "width: 75px;\n"
                                        "height: 50px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "border: None;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: silver;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: red;\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "background-color: white;\n"
                                        "width: 75px;\n"
                                        "height: 50px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "border: None;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: silver;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: red;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
                                        "background-color: white;\n"
                                        "width: 75px;\n"
                                        "height: 50px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "border: None;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: silver;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: red;\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
                                         "background-color: white;\n"
                                         "width: 75px;\n"
                                         "height: 50px;\n"
                                         "font-size: 14px;\n"
                                         "font-weight: bold;\n"
                                         "border: None;\n"
                                         "text-align: center;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "background-color: silver;\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "background-color: red;\n"
                                         "}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 3, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                        "background-color: white;\n"
                                        "width: 75px;\n"
                                        "height: 50px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "border: None;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: silver;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: red;\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "background-color: white;\n"
                                        "width: 75px;\n"
                                        "height: 50px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "border: None;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: silver;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: red;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
                                        "background-color: white;\n"
                                        "width: 75px;\n"
                                        "height: 50px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "border: None;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: silver;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: red;\n"
                                        "}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
                                        "background-color: white;\n"
                                        "width: 75px;\n"
                                        "height: 50px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "border: None;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: silver;\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color: red;\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 100, 241, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "7"))
        self.pushButton_2.setText(_translate("Dialog", "8"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_9.setText(_translate("Dialog", "3"))
        self.pushButton_10.setText(_translate("Dialog", "0"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_3.setText(_translate("Dialog", "9"))
        self.pushButton_8.setText(_translate("Dialog", "2"))
        self.pushButton_7.setText(_translate("Dialog", "1"))
