# Generated by Django 3.1.7 on 2021-04-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('subscrible', models.TextField(verbose_name='Описание')),
                ('program', models.TextField(verbose_name='Программа')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('img', models.ImageField(upload_to='photos/Номера/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Экскурссия',
                'verbose_name_plural': 'Экскурссия',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('subscrible', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('img', models.ImageField(upload_to='photos/Меню/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуга',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('subscrible', models.TextField(verbose_name='Описание')),
                ('enum', models.IntegerField(verbose_name='Количество мест')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('img', models.ImageField(upload_to='photos/Номера/', verbose_name='Фото')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номер',
            },
        ),
    ]
