# Generated by Django 3.1.7 on 2021-05-30 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
        ),
        migrations.AlterModelOptions(
            name='excursion',
            options={'ordering': ['id'], 'verbose_name': 'Экскурссия', 'verbose_name_plural': 'Экскурссии'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='numbers',
            options={'ordering': ['id'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='numbers',
            name='service',
        ),
        migrations.RemoveField(
            model_name='numbers',
            name='title',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='img',
            field=models.ImageField(upload_to='photos/Экскурсии/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='enum',
            field=models.CharField(choices=[('1', '1-но комнатный'), ('2', '2-х комнатный'), ('4', '4-х комнатный')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(verbose_name='Ключ')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные')),
                ('count', models.IntegerField(default=0, verbose_name='Покупки')),
                ('orders_number_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.orders_number', verbose_name='Id заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartProducts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
    ]
