# Generated by Django 3.1.7 on 2021-06-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210615_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='enum',
            field=models.CharField(choices=[('1', '1-но комнатный'), ('2', '2-х комнатный'), ('3', '3-х комнатный'), ('4', '4-х комнатный')], default='1', max_length=1),
        ),
    ]
