# Generated by Django 3.1.7 on 2021-06-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210617_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders_number',
            new_name='Order_numbers',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='orders_number_id',
            new_name='order_numbers_id',
        ),
    ]
