# Generated by Django 3.1.7 on 2021-06-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210617_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_numbers',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Заказано'),
        ),
        migrations.AddField(
            model_name='order_numbers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.orders', verbose_name='Заказчик'),
            preserve_default=False,
        ),
    ]
