# Generated by Django 3.1.7 on 2021-06-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210621_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_numbers_id',
        ),
        migrations.AddField(
            model_name='order_numbers',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество товаров'),
        ),
        migrations.AlterField(
            model_name='order_numbers',
            name='data',
            field=models.JSONField(default=1, verbose_name='Заказано'),
            preserve_default=False,
        ),
    ]
